development:
  adapter: postgresql
  encoding: utf8
  database: conichi_dev
  pool: 5
  username: over
  password: 
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: conichi_test
  pool: 5
  username: over
  password: 
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['DB_NAME'] %>
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  host: <%= ENV['DB_HOST'] %>

